org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
android.useAndroidX=true
android.r8.maxWorkers=4
android.r8.gradual.support=true
kotlin.daemon.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m
org.gradle.workers.max=2
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE
kotlin.code.style=official
